### ISSUE TITLE
Use uuid for EFI_VOLUME

### ISSUE THREAD

**Issue by Dertosh** [slytomcat/UEFI-Boot#2]
I think add option UUID for EFI_VOLUME will be useful, because using UUID is safer then using device name. Command for convert UUID to device name:

blkid -U <uuid>

**Comment by slytomcat** [comment]
Actually EFS volume have partition code EF00
It can be seen in output of gdisk -l /dev/sda
fdisk shows it as "EFI System"

I think it is better way to find EFS.

2017-02-25 19:07 GMT+03:00 Dertosh <notifications@github.com>:

**Comment by Dertosh** [comment]
OK. It is better way. Good idea.

**Comment by slytomcat** [comment]
`echo "/dev/sda$(gdisk -l /dev/sda | sed -n "s/[ \t]*\([0-9][0-9]*\).*EF00/\1/p")"
`
Give me my EFS partition.

May be it is not optimal solution (I'm not a bash script expert) but it works!

**Comment by slytomcat** [comment]
Only one concern - I'm not sure that gdisk is available from box on all (at least on all popular) Linux distributions

**Comment by Dertosh** [comment]
I searching information about get EFI partition, but I can't found better solution. I think gdisk is available from box on all popular Linux distributions.

**Comment by slytomcat** [comment]
I've added the feature to get the EFS partition number from gdisk in https://github.com/slytomcat/UEFI-Boot/commit/4ca5378d9dc767b0468de5d1e0d4f109e3464f27. 

But disk is /dev/sda if not overridden by EFI_DISK value in /etc/uefiboot.conf
